name: Build and Deploy to S3

# PREREQUISITES:  You must set the following Secrets in your GitHub Repository (settings/secrets and variables):
# * AWS_ROLE_ARN
# * ROLE_EXTERNAL_ID - value in the secret must = value in the role's condition.
# * S3_UPLOAD_BUCKET
#
# Helpful background article:  https://aws.amazon.com/blogs/security/use-iam-roles-to-connect-github-actions-to-actions-in-aws/

on:
  push:
    branches:
      - main
    paths:
      - 'aws-deploy/**'

jobs:
  buildAndPushToS3:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for OIDC authentication.
      contents: read   # Required to clone the repository.

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Node.js
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 21 # Use the version of Node.js compatible with your project

    # Step 3: Install dependencies and build the project
    - name: Install dependencies and build
      run: |
        cd aws-deploy 
        npm ci
        npm run build

    # Step 4: Configure AWS credentials using OIDC
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-region: us-east-1  # Replace with your AWS region
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-external-id: ${{ secrets.ROLE_EXTERNAL_ID }}

    # Step 5: Deploy to S3
    - name: Deploy to S3
      run: |
        aws s3 sync /dist s3://${{ secrets.S3_UPLOAD_BUCKET }} --delete
